medical_histories:
    usuarios:
        usuario: 
            type: varchar
            size: 50
            required: true
        contrase√±a: 
            type: varchar
            size: 50
            required: true
        correo: 
            type: varchar
            size: 50
            required: true
        creacion: 
            type: date
            required: true
        id_persona: 
            type: int
            join: personas
            required: true